name: Publish

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Git configuration
        working-directory: ${{ inputs.packageBasePath }}${{ inputs.package }}
        shell: bash
        run: |
          git config user.email "philipp@bendcircular.com"
          git config user.name "Philipp Litzenberger"

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn version --patch

      - name: Publish stuff
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
