name: Publish

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Git configuration
        run: |
          git config user.email "philipp@bendcircular.com"
          git config user.name "Philipp Litzenberger"

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install

      - name: Configure Yarn
        run: |
          yarn config set version-git-message "ci(CD): Increment npm package version v%s"
          yarn config set version-tag-prefix "@bendcircular/sample-npm-package@"

      - name: Increment package version
        run: yarn version --patch

      - name: Update tags
        run: |
          git push
          git push --tags

      - name: Publish stuff
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
